name = "manfalout-secure-gateway"
main = "worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "manfalout-portal-db"
database_id = "9e352b72-7830-4bb4-9811-85802c420a94"